### ISSUE TITLE
Add README.md template to the root files

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/grunt-init-laxar-activity#4]
# {%= title %}

{%= description %}

## Content
* [Usage](#usage)
* [Features](#features)
* [Integration](#integration)
* [References](#references)
    
### Installation
For installation instruction take a look at the [LaxarJS documentation](https://github.com/LaxarJS/laxar/blob/master/docs/manuals/installing_widgets.md).

### Configuration Example
TODO: Show required configuration. Example:
```json
{
   "widget": "{%= name %}_{%= type %}",
   "features": {
      "myFeature": {
         "resource": "topic-subtopic"
      }
   }
}
```
Use this configuration on a page to get a {%= title %} instance.
TODO: Describe specifics of the example.

For full configuration options refer to the [widget.json](widget.json).

## Features
TODO: Short feature description in imperative form. Followed by the name of the configuration section. Example:

### 1. Allow user to enter foo data (myFeature)
TODO: List individual requirements. Example:
*R1.1* The topic ID of the resource to be displayed by the widget must be configurable.
*R1.2* The resource MUST be interpreted as (possibly internationalized) foo data.
*R1.3* The Widget MUST display the total amount of foo as a decimal number with two digits precision.
...

### 2. Allow user to save changes to the server (myStorage)
*R2.1* ...

### Patterns
The {%= type %} supports the following event patterns as specified by the [LaxarJS Patterns] document.

#### Resources
TODO: List individual topics or delete the section. Example:
* Resource: `myFeature.resource`
   * Role: TODO: Master or Slave
   * Access: TODO: Read and/or Write
   * Description: Contains the foo data.

#### Actions
TODO: List individual topics or delete the section. Example:
* Action: `myStorage.action`
   * Role: TODO: Sender or Receiver
   * Description: Causes the widget to save the data.

#### Flags
TODO: List individual topics or delete the section.
* Flag: `myFeature.flag`
   * Role: TODO: Sender or Receiver
   * Description: The flag is `true` while transmitting data.

#### Locales
TODO: List non-default locales or delete the section.

## References
The following resources are useful or necessary for the understanding of this document.
The links refer to the latest version of the documentation.
Refer to the [bower.json](bower.json) for the specific version that is normative for this document.

* [LaxarJS Concepts]
* [LaxarJS Patterns]
TODO: Include if i18n is supported:
* [LaxarJS i18n]

[LaxarJS Concepts]: https://github.com/LaxarJS/laxar/blob/master/docs/concepts.md "LaxarJS Concepts"
[LaxarJS Patterns]: https://github.com/LaxarJS/laxar_patterns/blob/master/docs/index.md "LaxarJS Patterns"
TODO: Include if i18n is supported:
[LaxarJS i18n]: https://github.com/LaxarJS/laxar/blob/master/docs/manuals/i18n.md "LaxarJS i18n"

**Comment by x1B** [comment]
Implemented on `master` (`v0.4.0`).
